# Use the official Apache image
FROM httpd:latest

LABEL ENV="3-zafer"
# RUN: Create a simple HTML file directly during the build
# This overwrites the default "It works!" page
RUN echo "<html> \
    <head><title>My Docker App</title></head> \
    <body> \
        <h1>Hello from Docker!</h1> \
        <p>This page was created using the RUN command.</p> \
    </body> \
    </html>" > /usr/local/apache2/htdocs/index.html

# CMD: Start Apache in the foreground
CMD ["httpd-foreground"]